// <auto-generated />
using EmployeeListApp.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeListApp.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240913013128_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeListApp.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Address = "Santa Maria, Bulacan",
                            Email = "josh09@gmail.com",
                            FirstName = "Joshua",
                            Gender = 0,
                            LastName = "Canapi",
                            MiddleName = "Fernandez",
                            PhoneNumber = "09503334244",
                            Status = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            Address = "Santa Maria, Bulacan",
                            Email = "james09@gmail.com",
                            FirstName = "James",
                            Gender = 0,
                            LastName = "Canapi",
                            MiddleName = "Fernandez",
                            PhoneNumber = "095055635412",
                            Status = 1
                        },
                        new
                        {
                            EmployeeId = 3,
                            Address = "Santa Maria, Bulacan",
                            Email = "mich09@gmail.com",
                            FirstName = "Mich",
                            Gender = 1,
                            LastName = "Canapi",
                            MiddleName = "Fernandez",
                            PhoneNumber = "09505433362",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
